### ISSUE TITLE
Workflow won't trigger/complete on Linux server(with no GPU)

### ISSUE THREAD

**Issue by justinhorton2003** [Project-MONAI/monai-deploy#137] opened 2023-07-23 18:05 UTC
I'm trying to remotely deploy monai-deploy-express on a Linux development server that doesn't have an NVIDIA GPU currently. Seeing as, seemingly, the sample workflows (Lung Seg) provided in the deploy express documentation completed on my own machine with CPU power (no GPU usage spike), I thought deploying to a Linux server without a dedicated GPU would be fine. Creating and running the containers on the remote server went fine, I defined the workflows and got back Workflow IDs and uploaded the CT data to Orthanc. But, when I sent to DICOM modality, the segmentation task would never finish and return the segmented images. I checked docker container list -a but couldn't find the container MONAI Lung Seg which would be responsible for the task. I tried adding NVIDIA Runtime to the Docker Daemon, installing CUDA and NVIDIA Toolkit, to see if the workflow would at least trigger then (even though there is no NVIDIA GPU). It did trigger and I could see the MONAI Lung Seg container running, but nothing would ever complete. How can I make monai deploy express execute and complete at least the sample workflows on my GPU-less remote Linux server? Also, when I do docker logs and the container ID for the Lung Seg container it doesn't display anything (maybe @mocsharp  can swoop in and save the day again) Cheers

**Comment by SameerShanbhogue** [comment] 2023-07-29 06:55
Similar Issue

No final output.

![image](https://github.com/Project-MONAI/monai-deploy/assets/84760553/d945160a-d020-4d18-9237-5002d2ce6e1f)


![image](https://github.com/Project-MONAI/monai-deploy/assets/84760553/6db2ddf3-9d76-4380-8a37-4a9b4394dd0a)

**Comment by SameerShanbhogue** [comment] 2023-07-29 06:57
Is GPU mandated for Monai Deploy Express setup?

**Comment by mocsharp** [comment] 2023-08-04 16:58
Hi @justinhorton2003 @SameerShanbhogue, @Shambhuraj11 

Could you please share the version of MDE that you are running?

According to @MMelQin, the Lung Seg workflow should run on CPU. 


I also tried the latest (0.4.0), after I submit the workflow and send the dataset from Orthanc.  I find the docker container that the Task Manager started:

```
docker container ls -a
CONTAINER ID   IMAGE                                                           COMMAND                  CREATED             STATUS                          PORTS                                                                                                                                                 NAMES
39309f19f86   ghcr.io/mmelqin/monai_ai_lung_seg_app:1.0                       "/bin/bash -c 'pytho…"   21 seconds ago   Up 19 seconds              6006/tcp, 8888/tcp                                                                                                                                    0ae77d9a-e14c-4c75-963a-b5f24a2ad9c0
b516a31be9d3   ghcr.io/mmelqin/monai_ai_livertumor_seg_app:1.0                 "/bin/bash -c 'pytho…"   2 minutes ago       Exited (0) About a minute ago                                                                                                                                                         7c65f7ec-2eac-4829-ba43-6210a77e03e0
```

I was able to see the logs from the containers and the segmentation output in Orthanc after a few minutes.


If possible, please attach the logs for us to investigate:

```
docker logs mdl-ig> mdl-ig.txt
docker logs mdl-wm > mdl-wm.txt
docker logs mdl-tm > mdl-tm.txt
```

Thank you!

/cc @JHancox

**Comment by JHancox** [comment] 2023-08-04 17:09
Sorry to hear of this issue.
Unfortunately I'll be on vacation for a couple of weeks in about 5 mins time! If still on-going, will look into this when I return (>=21st August).

**Comment by MMelQin** [comment] 2023-08-04 18:45
> I'm trying to remotely deploy monai-deploy-express on a Linux development server that doesn't have an NVIDIA GPU currently. Seeing as, seemingly, the sample workflows (Lung Seg) provided in the deploy express documentation completed on my own machine with CPU power (no GPU usage spike), I thought deploying to a Linux server without a dedicated GPU would be fine. Creating and running the containers on the remote server went fine, I defined the workflows and got back Workflow IDs and uploaded the CT data to Orthanc. But, when I sent to DICOM modality, the segmentation task would never finish and return the segmented images. I checked docker container list -a but couldn't find the container MONAI Lung Seg which would be responsible for the task. I tried adding NVIDIA Runtime to the Docker Daemon, installing CUDA and NVIDIA Toolkit, to see if the workflow would at least trigger then (even though there is no NVIDIA GPU). It did trigger and I could see the MONAI Lung Seg container running, but nothing would ever complete. How can I make monai deploy express execute and complete at least the sample workflows on my GPU-less remote Linux server? Also, when I do docker logs and the container ID for the Lung Seg container it doesn't display anything (maybe @mocsharp can swoop in and save the day again) Cheers

Thank you @justinhorton2003 for your question and the steps to isolate the issue. As you had verified, the example MONAI Application Package (MAP) works without GPU, though you must have noticed, the inference takes a very long time, ~30 mins; with a GPU (with 6+ GB of memory), the whole application, DICOM in and DICOM results out, finishes in less than 90s.

Anyway, the issue observed when exercising the MONAI Deploy Express is likely around the launching of the MAP container by the Task Manager plugin, a component in MDE. It is in fact the LIFECYCLE MANAGEMENT of the container, as evident in the [workflow definition for the lung seg MAP](https://github.com/Project-MONAI/monai-deploy/blob/main/deploy/monai-deploy-express/sample-workflows/lung-seg.json),  the container TIMEOUT, `akatask_timeout_minutes ` is set at 5mins.
    
Please bump up this time out value based on the time you had observed when running the MAP standalone with CPU only, in the MDE container. Setting it to 0 also works but not 

@justinhorton2003 @mocsharp

**Comment by MMelQin** [comment] 2023-08-04 18:51
> 

Hi @SameerShanbhogue thanks for the question. Not sure if the same error you saw still persists. The Task Manager failed to launch the MAP container due to its failure to load libnvidai-ml.so. Also please see my reply above with regard to the long execution time of MAP container if on CPU, and the solution. @mocsharp @JHancox

**Comment by SameerShanbhogue** [comment] 2023-08-05 04:22
file:///home/vboxuser/Downloads/monai-deploy-main/deploy/monai-deploy-express/mdl-ig.txt
-26:-49:63:63
file:///home/vboxuser/Downloads/monai-deploy-main/deploy/monai-deploy-express/mdl-tm.txt
file:///home/vboxuser/Downloads/monai-deploy-main/deploy/monai-deploy-express/mdl-wm.txt

**Comment by SameerShanbhogue** [comment] 2023-08-05 04:25
[mdl-ig.txt](https://github.com/Project-MONAI/monai-deploy/files/12266101/mdl-ig.txt)
[mdl-tm.txt](https://github.com/Project-MONAI/monai-deploy/files/12266102/mdl-tm.txt)
[mdl-wm.txt](https://github.com/Project-MONAI/monai-deploy/files/12266103/mdl-wm.txt)
@mocsharp

**Comment by SameerShanbhogue** [comment] 2023-08-05 04:28
@mocsharp 
![image](https://github.com/Project-MONAI/monai-deploy/assets/84760553/799a79f1-b8c3-402c-81d6-6564963426f1)

**Comment by justinhorton2003** [comment] 2023-08-05 09:40
Hey! Thanks everyone for all the interaction. I believe I am running the latest version(0.4?), I pulled the repo a couple weeks ago. But I can double check in a bit. I'll also try the suggested solution. Thanks a lot @MMelQin @mocsharp and everyone else for responding.

**Comment by Shambhuraj11** [comment] 2023-08-07 04:44
Hii @mocsharp. Thanks for replying. I am also using the latest version (0.4). I will share log files that you asked for. I will also try to re-run the application and check for any errors from my side. Thank you

**Comment by Shambhuraj11** [comment] 2023-08-07 06:53
Hii I   built and re-run the liver-seg app from scratch just an hour ago. at that time docker container was created, but after some time I again built and re-run the application from scratch. At this time it has not created a docker container for application this time. I am attaching the logs file that you asked for and also attaching a screenshot
[mdl-ig.txt](https://github.com/Project-MONAI/monai-deploy/files/12272993/mdl-ig.txt)
[mdl-tm.txt](https://github.com/Project-MONAI/monai-deploy/files/12272996/mdl-tm.txt)
[mdl-wm.txt](https://github.com/Project-MONAI/monai-deploy/files/12272998/mdl-wm.txt)
![MicrosoftTeams-image](https://github.com/Project-MONAI/monai-deploy/assets/102733423/ee7557e6-c3b9-4ed3-bb67-fd1cb3f6b42a)

**Comment by SameerShanbhogue** [comment] 2023-08-26 13:01
Hi

I find the issue is related to pre-requisite environment stated for implementation NIVIDIA CUDA Toolkit and NVIDIA Container Toolkit which I believe requires GPU. After moving to AWS EC2 with GPU the issue gets resolved.

**Comment by MMelQin** [comment] 2023-10-09 21:40
@SameerShanbhogue Great to hear that issue was resolved, so I will mark this as closed.

**Closed by MMelQin** 2023-10-09 21:40 UTC
Labels: question, monai-deploy-express
